-- Data classification
--
-- Which columns hold protected health information, which merely identify a person, which
-- are operational, and which are secrets. The reviewer's first question about an
-- inventory is how anyone knows it is still true — so this is not a list kept beside the
-- schema. It is a table with a completeness check, and a column added later without a
-- classification fails that check rather than quietly joining the untracked set.
--
-- Applied after schema.sql. The inventory itself is generated by the view at the end.
--
-- The classes, and the line between them:
--
--   phi           Health information about a resident, or anything that identifies the
--                 resident it belongs to. A resident's name is PHI here — it is an
--                 identifier attached to a care record, which is what the term means.
--   identifying   Identifies a person who is not the patient. Staff and family contact
--                 details. Sensitive, subject to the same access control, but not PHI:
--                 a caregiver's email is not health information about a caregiver.
--   operational   Keys, timestamps, state, configuration. Reveals nothing on its own.
--   secret        Credentials. Never logged, never returned by an API, never in a backup
--                 that is less protected than the database.

CREATE TYPE data_class AS ENUM ('phi', 'identifying', 'operational', 'secret');

CREATE TABLE data_classification (
  table_name   text NOT NULL,
  column_name  text NOT NULL,
  class        data_class NOT NULL,
  note         text,
  PRIMARY KEY (table_name, column_name)
);

COMMENT ON TABLE data_classification IS
  'Source of the PHI inventory. Kept in the database rather than a document so that the
   inventory can be generated rather than maintained, and so that drift is a failing
   check rather than a discovery during review.';


-- ── facilities ─────────────────────────────────────────────────────────────────
-- A building is not a person. Nothing here is PHI.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('facilities','id','operational',NULL),
 ('facilities','name','operational','A business name, not a person.'),
 ('facilities','timezone','operational','Decides where a care day starts and ends.'),
 ('facilities','created_at','operational',NULL),
 ('facilities','updated_at','operational',NULL),
 ('facilities','archived_at','operational',NULL);


-- ── users ──────────────────────────────────────────────────────────────────────
-- Caregivers, managers and family members. None of them is the patient, so their
-- details identify without being health information. They are still access-controlled.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('users','id','operational',NULL),
 ('users','email','identifying','Login identity and the address invitations go to.'),
 ('users','password_hash','secret','Argon2id. Never returned, never logged.'),
 ('users','display_name','identifying','Staff or family name. Appears in a care record as the author, which does not make it the resident''s information.'),
 ('users','email_verified_at','operational',NULL),
 ('users','second_factor_enrolled_at','operational','When, not what. The factor itself is held by the platform that verifies it.'),
 ('users','last_seen_at','operational',NULL),
 ('users','created_at','operational',NULL),
 ('users','updated_at','operational',NULL),
 ('users','deactivated_at','operational',NULL);

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('user_tokens','id','operational',NULL),
 ('user_tokens','user_id','operational',NULL),
 ('user_tokens','purpose','operational',NULL),
 ('user_tokens','token_hash','secret','Only the hash is stored, so a database read cannot be replayed as a password reset.'),
 ('user_tokens','expires_at','operational',NULL),
 ('user_tokens','consumed_at','operational',NULL),
 ('user_tokens','created_at','operational',NULL);

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('sessions','id','operational',NULL),
 ('sessions','user_id','operational',NULL),
 ('sessions','refresh_hash','secret',NULL),
 ('sessions','device_label','identifying','Shown to the user when reviewing their own sessions.'),
 ('sessions','issued_at','operational',NULL),
 ('sessions','last_used_at','operational',NULL),
 ('sessions','expires_at','operational',NULL),
 ('sessions','idle_expires_at','operational','How long a phone left on a med cart stays useful, which is a different question from how long somebody may stay signed in.'),
 ('sessions','revoked_at','operational',NULL);


-- ── staff membership and assignment ────────────────────────────────────────────
-- Who works where, and who is responsible for whom. The assignment rows are
-- operational on their own, but they are the thing access control resolves from, so
-- they are protected as tightly as what they unlock.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('facility_members','id','operational',NULL),
 ('facility_members','facility_id','operational',NULL),
 ('facility_members','user_id','operational',NULL),
 ('facility_members','role','operational',NULL),
 ('facility_members','state','operational',NULL),
 ('facility_members','invited_by','operational',NULL),
 ('facility_members','started_at','operational',NULL),
 ('facility_members','ended_at','operational',NULL),
 ('facility_members','created_at','operational',NULL),
 ('facility_members','updated_at','operational',NULL);

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('assignments','id','operational',NULL),
 ('assignments','facility_id','operational',NULL),
 ('assignments','resident_id','operational','A resident identifier. Not health information by itself, but it is the key everything else hangs from.'),
 ('assignments','facility_member_id','operational',NULL),
 ('assignments','started_at','operational',NULL),
 ('assignments','ended_at','operational',NULL),
 ('assignments','created_at','operational',NULL);


-- ── residents ──────────────────────────────────────────────────────────────────
-- The patient. A name attached to a care record is PHI, and so is a baseline: saying
-- someone is usually confused is a statement about their health.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('residents','id','operational','Generated. Carries no meaning, which is why it is safe in a log line - and why a copy of this database re-keys it: the same uuid in a development copy and a production log line is a code assigned to the individual, which is a different thing entirely. See remap_key in environments.sql.'),
 ('residents','facility_id','operational',NULL),
 ('residents','display_name','phi','The resident''s name, held against their care record.'),
 ('residents','external_source','operational',NULL),
 ('residents','external_patient_id','phi','The clinical system''s own identifier for this person.'),
 ('residents','baseline_mood','phi','What is normal for them. A clinical observation.'),
 ('residents','baseline_appetite','phi',NULL),
 ('residents','baseline_sleep','phi',NULL),
 ('residents','admitted_on','phi','Admission to a care facility is health information.'),
 ('residents','departed_on','phi',NULL),
 ('residents','created_at','operational',NULL),
 ('residents','updated_at','operational',NULL);


-- ── family access ──────────────────────────────────────────────────────────────
-- The relation column is the subtle one: "child of resident X" says something about a
-- person's family circumstances, and it is attached to a patient record.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('resident_contacts','id','operational',NULL),
 ('resident_contacts','facility_id','operational',NULL),
 ('resident_contacts','resident_id','operational',NULL),
 ('resident_contacts','user_id','operational',NULL),
 ('resident_contacts','relation','phi','How this person is related to a resident in care. Attached to a patient, so it travels with them.'),
 ('resident_contacts','state','operational',NULL),
 ('resident_contacts','granted_by','operational',NULL),
 ('resident_contacts','granted_at','operational',NULL),
 ('resident_contacts','revoked_by','operational',NULL),
 ('resident_contacts','revoked_at','operational',NULL),
 ('resident_contacts','created_at','operational',NULL),
 ('resident_contacts','updated_at','operational',NULL);


-- ── the care record ────────────────────────────────────────────────────────────
-- All of it. This is the reason the rest of the file exists.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('care_days','id','operational',NULL),
 ('care_days','facility_id','operational',NULL),
 ('care_days','resident_id','operational',NULL),
 ('care_days','care_date','phi','The date a person received care.'),
 ('care_days','mood','phi',NULL),
 ('care_days','appetite','phi',NULL),
 ('care_days','sleep','phi',NULL),
 ('care_days','note','phi','Free text written by a caregiver. Assume it contains anything.'),
 ('care_days','hygiene_shower','phi',NULL),
 ('care_days','hygiene_grooming','phi',NULL),
 ('care_days','filed_by','operational',NULL),
 ('care_days','filed_at','operational',NULL),
 ('care_days','superseded_at','operational',NULL),
 ('care_days','amends_id','operational',NULL),
 ('care_days','created_at','operational',NULL),
 ('care_days','updated_at','operational',NULL);

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('care_day_meals','care_day_id','operational',NULL),
 ('care_day_meals','slot','phi',NULL),
 ('care_day_meals','happened','phi','Whether a person ate.'),
 ('care_day_meals','amount','phi','How much they ate.');

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('care_day_concerns','care_day_id','operational',NULL),
 ('care_day_concerns','concern','phi','A flagged clinical concern.');


-- ── medication ─────────────────────────────────────────────────────────────────

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('medication_events','id','operational',NULL),
 ('medication_events','facility_id','operational',NULL),
 ('medication_events','resident_id','operational',NULL),
 ('medication_events','care_date','phi',NULL),
 ('medication_events','slot','phi',NULL),
 ('medication_events','status','phi','Given, held or refused. A clinical fact.'),
 ('medication_events','occurred_at','phi','When a dose was administered.'),
 ('medication_events','recorded_at','operational','When the system was told, which is not the same thing.'),
 ('medication_events','source','operational',NULL),
 ('medication_events','source_ref','phi','A reference into a clinical system, resolvable to a patient.'),
 ('medication_events','recorded_by','operational',NULL),
 ('medication_events','detail','phi','What the supplemental dose was.'),
 ('medication_events','created_at','operational',NULL);


-- ── media ──────────────────────────────────────────────────────────────────────
-- The photograph is PHI. So is its path: object keys are derived from the resident, and
-- a path that leaks tells you who a stored image is of.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('media_objects','id','operational',NULL),
 ('media_objects','facility_id','operational',NULL),
 ('media_objects','resident_id','operational',NULL),
 ('media_objects','care_day_id','operational',NULL),
 ('media_objects','bucket','operational',NULL),
 ('media_objects','object_path','phi','Resolves to a photograph of a resident.'),
 ('media_objects','content_type','operational',NULL),
 ('media_objects','byte_size','operational',NULL),
 ('media_objects','checksum','operational',NULL),
 ('media_objects','uploaded_by','operational',NULL),
 ('media_objects','created_at','operational',NULL),
 ('media_objects','uploaded_at','operational','When the object was confirmed in the bucket. Null means the row is a place that was offered and never used.'),
 ('media_objects','deleted_at','operational',NULL);


-- ── audit ──────────────────────────────────────────────────────────────────────
-- The audit trail records that a resident's record was touched, which is itself
-- health information — someone has a care record. It does not record what the record
-- said, and the detail column is constrained to field names rather than values.

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('audit_events','id','operational',NULL),
 ('audit_events','occurred_at','operational',NULL),
 ('audit_events','actor_user_id','operational',NULL),
 ('audit_events','actor_role','operational',NULL),
 ('audit_events','facility_id','operational',NULL),
 ('audit_events','action','operational',NULL),
 ('audit_events','subject_type','operational',NULL),
 ('audit_events','subject_id','operational',NULL),
 ('audit_events','resident_id','phi','That this resident has a record which was accessed.'),
 ('audit_events','request_id','operational',NULL),
 ('audit_events','ip_hash','identifying','Hashed. Correlates a session without storing an address.'),
 ('audit_events','user_agent','operational',NULL),
 ('audit_events','detail','operational','Field names and identifiers only. An audit log that quotes the record it protects has become a second copy of it.');


-- ── retention ──────────────────────────────────────────────────────────────────

INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('retention_policies','facility_id','operational',NULL),
 ('retention_policies','care_record_days','operational',NULL),
 ('retention_policies','media_days','operational',NULL),
 ('retention_policies','audit_days','operational',NULL),
 ('retention_policies','care_record_basis','operational','What the number rests on, which is a citation rather than anything about a person.'),
 ('retention_policies','updated_by','operational',NULL),
 ('retention_policies','updated_at','operational',NULL);

-- The classification table classifies itself, so the completeness check below has
-- nothing to except.
INSERT INTO data_classification (table_name, column_name, class, note) VALUES
 ('data_classification','table_name','operational',NULL),
 ('data_classification','column_name','operational',NULL),
 ('data_classification','class','operational',NULL),
 ('data_classification','note','operational',NULL);


-- ════════════════════════════════════════════════════════════════════ the inventory
--
-- Generated, not written. This is what goes to the reviewer, and it cannot disagree with
-- the database because it is read from it.

CREATE VIEW phi_inventory AS
SELECT
  c.table_name,
  c.column_name,
  c.data_type,
  dc.class,
  dc.note
FROM information_schema.columns c
JOIN information_schema.tables t
       ON t.table_schema = c.table_schema AND t.table_name = c.table_name
      AND t.table_type = 'BASE TABLE'          -- views derive from these; classifying
                                               -- both would be a second list to drift
LEFT JOIN data_classification dc
       ON dc.table_name = c.table_name AND dc.column_name = c.column_name
WHERE c.table_schema = 'public'
ORDER BY (dc.class = 'phi') DESC NULLS FIRST, c.table_name, c.ordinal_position;

COMMENT ON VIEW phi_inventory IS
  'The PHI inventory for the review package. Unclassified columns sort to the top, so an
   omission is the first thing read rather than the last thing found.';


-- Every column in the schema must be classified. A new column arrives unclassified and
-- this returns it; the check below turns that into a failure rather than a footnote.
CREATE VIEW unclassified_columns AS
SELECT c.table_name, c.column_name
FROM information_schema.columns c
JOIN information_schema.tables t
       ON t.table_schema = c.table_schema AND t.table_name = c.table_name
      AND t.table_type = 'BASE TABLE'
LEFT JOIN data_classification dc
       ON dc.table_name = c.table_name AND dc.column_name = c.column_name
WHERE c.table_schema = 'public'
  AND dc.class IS NULL;
